# ===============================
# APPLICATION
# ===============================
spring.application.name=techtrack-backend
server.port=8080

# ===============================
# POSTGRESQL DATABASE
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/techtrack_db
spring.datasource.username=postgres
spring.datasource.password=root123
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ===============================
# JWT CONFIG
# ===============================
jwt.secret=TechTrack$G5Daal$SecretKey$2025$SpringBoot$JWT$Secure
jwt.expiration=86400000